"""Add PipelineTemplate and link to Job/Stage

Revision ID: 2b48e34abd3b
Revises: 9b971611763b
Create Date: 2026-02-19 16:07:45.532586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b48e34abd3b'
down_revision: Union[str, Sequence[str], None] = '9b971611763b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('jobs', sa.Column('pipeline_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'pipeline_templates', ['pipeline_template_id'], ['id'])
    op.add_column('pipeline_stages', sa.Column('pipeline_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'pipeline_stages', 'pipeline_templates', ['pipeline_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pipeline_stages', type_='foreignkey')
    op.drop_column('pipeline_stages', 'pipeline_template_id')
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'pipeline_template_id')
    op.drop_table('pipeline_templates')
    # ### end Alembic commands ###
