"""Add ScorecardTemplate and scorecard_template_id to Job

Revision ID: 339f5c1da193
Revises: 3496cc33aa16
Create Date: 2026-02-19 11:46:12.876268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339f5c1da193'
down_revision: Union[str, Sequence[str], None] = '3496cc33aa16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('scorecard_template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'jobs', 'scorecard_templates', ['scorecard_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'scorecard_template_id')
    # ### end Alembic commands ###
