"""Add details JSONB to ScheduledActivity

Revision ID: 3496cc33aa16
Revises: b3790e838679
Create Date: 2026-02-19 11:38:12.507862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3496cc33aa16'
down_revision: Union[str, Sequence[str], None] = 'b3790e838679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_activities', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_activities', 'details')
    # ### end Alembic commands ###
