"""Add rejection_reason

Revision ID: 4da4e5c3b0e5
Revises: 5299152cf67c
Create Date: 2026-02-23 13:18:06.255524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4da4e5c3b0e5'
down_revision: Union[str, Sequence[str], None] = '5299152cf67c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_requisitions', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_requisitions', 'rejection_reason')
    # ### end Alembic commands ###
