"""Add phone and location to users and invitations

Revision ID: 5161772a2077
Revises: 02bfbd7c0ed5
Create Date: 2026-02-25 09:54:06.643819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5161772a2077'
down_revision: Union[str, Sequence[str], None] = '02bfbd7c0ed5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_invitations', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('user_invitations', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('user_invitations', sa.Column('location', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'location')
    op.drop_column('users', 'phone')
    op.drop_column('user_invitations', 'location')
    op.drop_column('user_invitations', 'phone')
    op.drop_column('user_invitations', 'full_name')
    # ### end Alembic commands ###
