"""add_application_scoring_fields

Revision ID: 8342d0c9a488
Revises: e123456789ab
Create Date: 2026-02-12 17:32:05.743804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8342d0c9a488'
down_revision: Union[str, Sequence[str], None] = 'e123456789ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_applications', sa.Column('score_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('job_applications', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('job_applications', sa.Column('recommendation', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_applications', 'recommendation')
    op.drop_column('job_applications', 'overall_score')
    op.drop_column('job_applications', 'score_details')
    # ### end Alembic commands ###
