"""add Approved status to RequisitionStatus enum

Revision ID: ab676da7ad30
Revises: 4da4e5c3b0e5
Create Date: 2026-02-23 14:55:01.893578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab676da7ad30'
down_revision: Union[str, Sequence[str], None] = '4da4e5c3b0e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE requisitionstatus ADD VALUE IF NOT EXISTS 'Approved'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
