"""Add Job Requisition Models

Revision ID: ba37ef88d1d7
Revises: aaf123456789
Create Date: 2026-02-23 11:16:04.668128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba37ef88d1d7'
down_revision: Union[str, Sequence[str], None] = 'aaf123456789'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_requisitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('req_code', sa.String(), nullable=False),
    sa.Column('job_title', sa.String(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=False),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('max_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('has_equity_bonus', sa.Boolean(), nullable=True),
    sa.Column('budget_code', sa.String(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_HR', 'PENDING_OWNER', 'OPEN', 'FILLED', 'CANCELLED', name='requisitionstatus'), nullable=True),
    sa.Column('hiring_manager_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requisitions_id'), 'job_requisitions', ['id'], unique=False)
    op.create_index(op.f('ix_job_requisitions_req_code'), 'job_requisitions', ['req_code'], unique=True)
    op.create_table('requisition_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['requisition_id'], ['job_requisitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requisition_logs')
    op.drop_index(op.f('ix_job_requisitions_req_code'), table_name='job_requisitions')
    op.drop_index(op.f('ix_job_requisitions_id'), table_name='job_requisitions')
    op.drop_table('job_requisitions')
    # ### end Alembic commands ###
