"""Add is_deleted and fix schema

Revision ID: fe82398d1575
Revises: 8342d0c9a488
Create Date: 2026-02-17 13:19:26.088884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe82398d1575'
down_revision: Union[str, Sequence[str], None] = '8342d0c9a488'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'departments', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    # ### end Alembic commands ###
